Vagrantfile_old

# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.network "public_network"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.username = "vagrant"
  #config.ssh.password = 'vagrant'
  config.ssh.private_key_path=["~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false 
  # config.vm.provision "shell", inline: <<-SHELL
  #   yum update
  # SHELL
  config.vm.define "ans_jump", primary: true do |ans_jump|
    ans_jump.vm.network "private_network", ip: "192.168.50.20"
    ans_jump.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = "2"
      vb.name = "ans_jump_server"
    end
  #   ans_jump.vm.provision "shell", inline: <<-SHELL
  #     sudo yum update
  # SHELL
  end
  config.vm.define "ans_first", primary: true do |ans_first|
    ans_first.vm.network "private_network", ip: "192.168.50.21"
    ans_first.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = "2"
      vb.name = "ans_first_svr"
    end
  #   ans_first.vm.provision "shell", inline: <<-SHELL
  #     sudo yum update
  # SHELL
  end
  config.vm.define "ans_second", primary: true do |ans_second|
    ans_second.vm.network "private_network", ip: "192.168.50.22"
    ans_second.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = "2"
      vb.name = "ans_second_svr"
    end
  #   ans_second.vm.provision "shell", inline: <<-SHELL
  #     sudo yum update
  # SHELL
  end
end
  #
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
#end